### PR TITLE
feat: support cpu

### PR DESCRIPTION
**Pull request by yihong0618**

### CODE REVIEW

**Comment by yihong0618** [comment]
Also add `requirements.txt`

**Review by ljsabc — APPROVED** [review]
Thanks very much for this simple yet effective pull req.

**Comment by yihong0618** [comment]
> Thanks very much for this simple yet effective pull req.

Thank you~

**Comment by yihong0618** [comment]
@ljsabc 

Can I ask why close instead of merge?

**Comment by ljsabc** [comment]
> @ljsabc
> 
> Can I ask why close instead of merge?

my bad. I did not sleep well last night.

**Comment by yihong0618** [comment]
> > @ljsabc
> > Can I ask why close instead of merge?
> 
> my bad. I did not sleep well last night.

Thanks^_^

**Comment by ljsabc** [comment]
> > > @ljsabc
> > > Can I ask why close instead of merge?
> > 
> > 
> > my bad. I did not sleep well last night.
> 
> Thanks^_^

Always welcome.

**Pull request merged**
